# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 174b46a88fa2e9ec1a48109d1c4819dc60659e29f8ea3a1c107c8be0381a027d4c951f307c9f6efa7046eca2b565fba6d75744c09a8738bf5b6eed16e0a37be5

test:
  secret_key_base: 36242991495500f376a7fa91130cf28d4555dab261f17c0aa582d130890ce559b2e5c4fe973539322949597cc0428c7f984a389567ab688faf0567561481b5de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
